### ISSUE TITLE
Navbar

### ISSUE THREAD

**Issue by itschiaras** [itschiaras/vue-game-creator#2]

**Comment by itschiaras** [comment]
git fetch origin
git checkout 2-navbar

**Comment by MarcoBione** [comment]
Reopened for fix navbar toggler button

**Comment by MarcoBione** [comment]
Added BootstrapJS @ index.html CDN

**Comment by MarcoBione** [comment]
Reopened for add name on navbar + color white (temporary)

**Comment by MarcoBione** [comment]
Added color to nav links
